# Generated by Django 5.1.2 on 2024-10-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("link", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links_model",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
