# Generated by Django 5.0.1 on 2024-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_alter_links_model_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='links_model',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='links_model',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
