# Generated by Django 5.0.1 on 2024-11-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_alter_links_model_name'),
        ('link', '0004_links_model_image_url_alter_links_model_name'),
    ]

    operations = [
    ]
