# Generated by Django 5.0.1 on 2024-10-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('old_price', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
